### ISSUE TITLE
Unable to build ruby on el:7

### ISSUE THREAD

**Issue by openface** [crohr/buildcurl#7]
https://buildcurl.com/?recipe=ruby&version=2.1.3&target=el%3A7&prefix=%2Fusr%2Flocal

```
Building ruby 2.1.3 el:7 /usr/local...

-> [ruby] -> Building ruby 2.1.3...
-> [ruby] % Total % Received % Xferd Average Speed Time Time Time Current
-> [ruby] Dload Upload Total Spent Left Speed
-> [ruby]
-> [ruby] -> [libyaml] -> Building libyaml 0.1.7...
-> [ruby] -> [libyaml] /tmp/tmp.VlO10TtLyc /app
-> [ruby] -> [libyaml]
-> [ruby] -> [libyaml] gzip: stdin: not in gzip format
-> [ruby] -> [libyaml] tar: Child returned status 1
-> [ruby] -> [libyaml] tar: Error is not recoverable: exiting now
-> [ruby] Build failed
-> [ruby]
-> [ruby] gzip: stdin: unexpected end of file
-> [ruby] tar: Child returned status 1
-> [ruby] tar: Error is not recoverable: exiting now

Build failed
```

This seems to have stopped working just a few days ago.

This is impacting our builds that rely on pkgr 1.8.0:

```
$ pkgr package . --tmpdir=/var/tmp --buildpack=https://github.com/pkgr/heroku-buildpack-ruby.git
-----> Ruby app
Traceback (most recent call last):
	5: from /home/vagrant/.pkgr/buildpacks/custom/c63bb174e4c4221f64348e2f0ef9411fc4dff21d/heroku-buildpack-ruby/bin/support/download_ruby:14:in `<main>'
	4: from /home/vagrant/.pkgr/buildpacks/custom/c63bb174e4c4221f64348e2f0ef9411fc4dff21d/heroku-buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `fetch_unpack'
	3: from /home/vagrant/.pkgr/buildpacks/custom/c63bb174e4c4221f64348e2f0ef9411fc4dff21d/heroku-buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `chdir'
	2: from /home/vagrant/.pkgr/buildpacks/custom/c63bb174e4c4221f64348e2f0ef9411fc4dff21d/heroku-buildpack-ruby/lib/language_pack/installers/heroku_ruby_installer.rb:22:in `block in fetch_unpack'
	1: from /home/vagrant/.pkgr/buildpacks/custom/c63bb174e4c4221f64348e2f0ef9411fc4dff21d/heroku-buildpack-ruby/lib/language_pack/fetcher.rb:24:in `fetch_untar'
/home/vagrant/.pkgr/buildpacks/custom/c63bb174e4c4221f64348e2f0ef9411fc4dff21d/heroku-buildpack-ruby/lib/language_pack/shell_helpers.rb:49:in `run!': Command: 'set -o pipefail; curl -L --get --fail --retry 3 buildcurl.com -d recipe=ruby -d version=2.4.1 -d target=$TARGET -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Any ideas @crohr ?

**Comment by crohr** [comment]
@openface it's just been fixed. Can you retry?

**Comment by openface** [comment]
Looks good!   Thanks for the prompt response and for this great service.
